# Generated by Django 6.0.2 on 2026-02-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_category_restaurant_alter_restaurant_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='phone',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
